= B21 Documentation
:toc:
:toclevels: 3
:sectnums:
:stem:

== B21: Divide By Zero Exception

Aharoni et al.

=== Description
This model will test the Divide By Zero exception flag. For the operations divide and remainder, a test case will be created for each of the possible combinations from the following table:

[cols="2*"]
|===
| First Operand  | Second Operand

| 0  | 0
| Random non-zero number | Random non-zero number
| Infinity | Infinity
| NaN  | NaN
|===

*Number of tests:*

*Precisions Supported:* `BF_16`, `FP_16`, `FP_32`, `FP_64`, `FP_128`

*Operations Supported:* `Divide`, `Remainder`

== Implementation

=== Definitions
`max_exp`:: the maximum exponent value based on precision
`min_exp`:: the minimum normal exponent value based on precision
`m_bits`:: the number of mantissa bits based on precision
`a`:: operand 1
`b`:: operand 2
`a_exp`:: value of `a`’s exponent, range is generally restricted to [`min_exp`, `max_exp`]
`b_exp`:: value of `b`’s exponent, range is generally restricted to [`min_exp`, `max_exp`]
`a_mantissa`:: the value of `a`’s mantissa
`b_mantissa`:: the value of `b`’s mantissa
`m_bits_left`:: the number of mantissa bits left for an operand. If the operand’s exponent is subnormal, stem:["m_bits_left" = "min_exp" - "operand_exp"]. If the operand’s exponent is normal, stem:["m_bits_left" = "m_bits"].
`max_mantissa`:: the largest possible value for the mantissa, stem:[(2^"bits_left") - 1]

== Operations

=== Two operands
* Divide
* Remainder

=== Rounding Modes

* Round Near Even
* Round To Min Mag
* Round To Min
* Round To Max
* Round Near Max Mag
* Round To Odd

=== General Implementation
Each test presents a different requirement on the result. Based on this requirement, each script determines the desired output exponent, sign, and mantissa based on the following information:

==== Values

[cols="3*"]
|===
| Value | Biased Exponent  | Mantissa

| Zero  | All zeros | All zeros
| Random non-zero Number | stem:[ \ne 0] | stem:[\mathbb{R}]
| Infinity  | All ones | All zeros
| NaN  | All ones | stem:[ \ne 0]
|===

== Specific Test Procedure
Each test has different requirements on the output exponent, sign, and mantissa, as shown in <<General Implementation>>. Each test performing the same operation is developed using similar procedures, as outlined below:

=== Operations: Division and Remainder

==== General Form

== Test Count Breakdown
.Test Count Breakdown
[cols="3,1", options="header"]
|===
| Category | Total

| Number of operations | 2
| Number of precisions | 5
| Rounding Modes | 5
| Vectors generated per test | 16
| *Summary* (2 × 5 × 5 × 16) | *800*
|===

_*Differs from Aharoni test count_
